version: '3.7'

services:

  neo4j:
    environment:
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
    volumes:
      - ./neo4j/plugins:/plugins
      - ./local/data/db/neo4j/neuprint:/data
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 12G
        reservations:
          cpus: '2'
          memory: 12G
    ports:
      - 7474:7474
      - 7687:7687

  neuprinthttp:
    image: neuprinthttp:test
    volumes:
      - ./local/opt/app/neuprinthttp/conf/:/app/config
      - ./local/opt/app/neuprinthttp/auth:/app/auth
      - ./local/opt/www/neuprintexplorer/current:/app/www/neuprintexplorer

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./local/etc/nginx/ssl/:/etc/nginx/ssl/
    ports:
      - 80:80
      - 443:443
