version: '3.7'

services:

  neo4j:
    image: gcr.io/sandbox-220614/connectome-neuprint/neo4j:3.5
    networks:
      - neuprint-net
    healthcheck:
      test: curl -i http://neo4j:7474 2>&1 | grep -c -e '200 OK'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  neuprinthttp:
    image: gcr.io/sandbox-220614/connectome-neuprint/neuprinthttp:1.7.7
    networks:
      - neuprint-net
    depends_on: 
      - neo4j

  nginx:
    image: nginx:1.15-alpine
    networks:
      - neuprint-net
    depends_on:
      - neuprinthttp

networks:
  neuprint-net:
