version: '3.7'

services:

  neo4j:
    environment:
      - NEO4J_dbms_memory_heap_initial__size=2G
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=4G
      - NEO4J_read_only=true
      - NEO4J_PASSWD=${NEO4J_PASSWD}
    volumes:
      - ./neo4j/plugins:/plugins
      - /data/db/neo4j/neuprint:/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"
    deploy:
      resources:
        limits:
          cpus: '32'
          memory: 120G
        reservations:
          cpus: '32'
          memory: 120G


  neuprinthttp:
    volumes:
      - /opt/app/neuprinthttp/conf/:/app/config
      - /opt/app/neuprinthttp/auth:/app/auth
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"

  nginx:
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/nginx/ssl/:/etc/nginx/ssl/
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
